// AccCoop UDP transport: publishes the local player sample and receives the peer's.
// All functions are called from the game thread (the PlayerTransform callback) except
// configure(), which the config watcher thread calls on reload.
#pragma once

#include <cstdint>
#include <string>
#include <vector>

namespace games::ac::blackflag::coop {

struct NetConfig {
    bool          enabled     = false;
    std::string   remote_host = "127.0.0.1";
    std::uint16_t remote_port = 27700;
    std::uint16_t local_port  = 27700;
    std::uint32_t client_id   = 1;
    float         send_hz     = 20.0F;
    std::string   player_name = "player";
    bool          is_host     = false;
};

struct RemotePlayer {
    bool          valid     = false;
    std::uint32_t client_id = 0;
    float         px = 0.0F;
    float         py = 0.0F;
    float         pz = 0.0F;
    float         qx = 0.0F;
    float         qy = 0.0F;
    float         qz = 0.0F;
    float         qw = 1.0F;
    std::uint32_t tick_ms = 0;
    std::uint32_t anim_state = 0; // packed phase<<16 | flags<<8 | hang (B4)
};

// C1 session state: host/join handshake result.
struct SessionInfo {
    bool          enabled     = false;
    bool          is_host     = false;
    bool          established = false; // handshake completed
    std::uint32_t session_id  = 0;     // generated by the host
    std::uint32_t peer_id     = 0;     // the other player's client id
    std::string   peer_name;
    std::uint32_t self_id     = 0;
};

// One received/queued event (payload opaquely defined by EventKind).
struct CoopEvent {
    std::uint16_t kind    = 0;
    std::uint16_t len     = 0;
    std::uint32_t event_id = 0;
    std::uint32_t from     = 0;
    std::uint8_t  data[40] = {};
};

// (Re)binds the socket and resolves the destination. Safe to call repeatedly; an
// empty/disabled config closes any existing socket.
void configure(const NetConfig &cfg);
void shutdown();

// Sends the local sample, throttled to NetConfig::send_hz. No-op when disabled.
// anim_state packs the locomotion/parkour state (0 idle,1 walk,2 jog,3 sprint,4 climb).
void publish(float px, float py, float pz,
             float qx, float qy, float qz, float qw,
             std::uint32_t anim_state);

// Non-blocking receive; updates latest_remote() and queues events.
void poll();

[[nodiscard]] auto latest_remote() -> RemotePlayer;
[[nodiscard]] auto session() -> SessionInfo;

// Event channel (reliable-ish: resend until acked via the sample's ack field).
// Returns false when disabled or the outbox is full. data may be null when len == 0.
auto send_event(std::uint16_t kind, const void *data, std::uint16_t len) -> bool;

// Drains received events (game thread). Returns the number queued into out.
auto drain_events(std::vector<CoopEvent> &out) -> std::size_t;

} // namespace games::ac::blackflag::coop
